services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./next_passa-a-bola
    container_name: next_passa-a-bola
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://next_passa-a-bola:8000
      - INTERNAL_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge